"""CQ -> C -> native binary (gcc)."""

from __future__ import annotations

import subprocess
import textwrap


class CGenError(Exception):
    pass


def c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


class CGen:
    def __init__(self):
        self.fns = []
        self.main = []

    def expr(self, node):
        k = node[0]
        if k == "num":
            return "i64", f"(int64_t){int(node[1])}"
        if k == "str":
            return "str", c_str(node[1])
        if k == "bool":
            return "bool", "1" if node[1] else "0"
        if k == "var":
            return "i64", node[1]
        if k == "binop":
            op, a, b = node[1], node[2], node[3]
            ta, ca = self.expr(a)
            tb, cb = self.expr(b)
            if op in {"==", "!=", "<", ">", "<=", ">="}:
                return "bool", f"({ca} {op} {cb})"
            return "i64", f"({ca} {op} {cb})"
        if k == "unary":
            t, c = self.expr(node[2])
            return t, f"(-({c}))" if node[1] == "-" else f"(!({c}))"
        if k == "call":
            if node[1][0] != "var":
                raise CGenError("C backend only supports direct calls")
            args = [self.expr(a)[1] for a in node[2]]
            return "i64", f"{node[1][1]}({', '.join(args)})"
        if k == "print":
            inner = node[1]
            t, c = self.expr(inner)
            if t == "str":
                return "i64", f'(printf("%s\\n", {c}), (int64_t)0)'
            if t == "bool":
                return "i64", f'(printf("%s\\n", {c} ? "true" : "false"), (int64_t)0)'
            return "i64", f'(printf("%lld\\n", (long long){c}), (int64_t)0)'
        if k == "expr":
            return self.expr(node[1])
        raise CGenError(f"unsupported expr {k}")

    def stmt(self, node, lines):
        k = node[0]
        if k == "block":
            for s in node[1]:
                self.stmt(s, lines)
            return
        if k == "print":
            _, c = self.expr(node)
            lines.append(c + ";")
            return
        if k == "let":
            name = node[1]
            t, c = self.expr(node[4])
            ctype = {"i64": "int64_t", "str": "const char*", "bool": "int", "res": "Result"}[t]
            lines.append(f"{ctype} {name} = {c};")
            return
        if k == "assign":
            _, c = self.expr(node[2])
            lines.append(f"{node[1]} = {c};")
            return
        if k == "if":
            _, cond = self.expr(node[1])
            lines.append(f"if ({cond}) {{")
            self.stmt(node[2], lines)
            lines.append("}")
            if node[3]:
                lines.append("else {")
                self.stmt(node[3], lines)
                lines.append("}")
            return
        if k == "return":
            t, c = self.expr(node[1])
            lines.append(f"return {c};")
            return
        if k == "expr":
            _, c = self.expr(node[1])
            lines.append(c + ";")
            return
        if k == "def":
            name, params, ret, body = node[1], node[2], node[3], node[4]
            ps = ", ".join(f"int64_t {p[0]}" for p in params) or "void"
            rty = "Result" if ret == "Result" else "int64_t"
            blines = []
            self.stmt(body, blines)
            if blines and not blines[-1].lstrip().startswith("return"):
                last = blines[-1].strip()
                if last.endswith(";") and "printf" not in last and " = " not in last and not last.startswith("if"):
                    blines[-1] = "return " + last
            body_c = "\n".join("  " + x for x in blines)
            self.fns.append(f"{rty} {name}({ps}) {{\n{body_c}\n}}")
            return
        if k in {"type", "iface", "import"}:
            return
        raise CGenError(f"unsupported stmt {k}")

    def compile_tree(self, tree) -> str:
        if tree[0] != "block":
            self.stmt(tree, self.main)
        else:
            for s in tree[1]:
                if s[0] == "def":
                    self.stmt(s, self.main if False else [])
                    self.stmt(s, [])
                    # defs go to self.fns via stmt
                if s[0] == "def":
                    if s not in getattr(self, "_seen", []):
                        self.stmt(s, [])
                else:
                    self.stmt(s, self.main)
        header = textwrap.dedent(
            """\\
            /* Generated by CQ 0.3 native compiler */
            #include <stdio.h>
            #include <stdint.h>
            #include <stdlib.h>
            typedef struct { int ok; int64_t value; const char* err; } Result;
            """
        )
        return header + "\n" + "\n\n".join(self.fns) + "\n\nint main(void) {\n" + "\n".join("  " + x for x in self.main) + "\n  return 0;\n}\n"


def compile_to_c(tree) -> str:
    return CGen().compile_tree(tree)


def build_native(tree, out_bin: str, keep_c: str | None = None) -> str:
    src = compile_to_c(tree)
    cpath = keep_c or (out_bin + ".c")
    with open(cpath, "w", encoding="utf-8") as f:
        f.write(src)
    r = subprocess.run(["gcc", "-O2", "-std=c11", cpath, "-o", out_bin], capture_output=True, text=True)
    if r.returncode != 0:
        raise CGenError("gcc failed:\n" + r.stderr)
    return cpath
